# Generated by Django 5.1.2 on 2025-02-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_product_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category_name',
        ),
    ]
