# Generated by Django 5.1.2 on 2025-02-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_category_id_product_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='category_id',
        ),
    ]
