# Generated by Django 5.1.2 on 2025-02-20 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_category_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_of_measurement', models.CharField(max_length=100)),
                ('unit_mesurement_symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_of_measure',
        ),
        migrations.AddField(
            model_name='product',
            name='unit_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.unit'),
            preserve_default=False,
        ),
    ]
