# Generated by Django 5.1.2 on 2025-02-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_unit_remove_product_unit_of_measure_product_unit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit_mesurement_symbol',
            new_name='unit_measurement_symbol',
        ),
    ]
