# Generated by Django 5.1.2 on 2025-02-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_unit_mesurement_symbol_unit_unit_measurement_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('supplier_title', models.CharField(max_length=10)),
                ('supplier_location', models.TextField()),
                ('supplier_number', models.IntegerField()),
                ('supplier_link', models.TextField()),
                ('supplier_rating', models.IntegerField()),
                ('supplier_media', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
