# Generated by Django 5.1.2 on 2025-02-21 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sale_date', models.DateTimeField(auto_created=True)),
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_number', models.IntegerField()),
                ('sale_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('saleItem_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField()),
                ('product_amount', models.IntegerField()),
                ('product_totalCost', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sales')),
            ],
        ),
    ]
