# Generated by Django 5.1.2 on 2025-02-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_sales_salesitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.AddField(
            model_name='sales',
            name='sale_paymentMethod',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
