# Generated by Django 5.1.2 on 2025-02-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_orderitem_order_id_sales_sale_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
