# Generated by Django 5.1.2 on 2025-02-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_orderitem_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=models.FileField(default=0, upload_to='uploads/productPhoto'),
            preserve_default=False,
        ),
    ]
