# Generated by Django 5.1.2 on 2025-02-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_product_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='sale_id',
        ),
        migrations.RemoveField(
            model_name='salesitem',
            name='product_amount',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
