# Generated by Django 5.1.2 on 2025-02-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_salesitem_sale_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_payment_method',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
