# Generated by Django 5.1.2 on 2025-02-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_transactions_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_receipt_id',
            field=models.CharField(default='AAAAAAAAAA', editable=False, max_length=10, unique=True),
        ),
    ]
