# Generated by Django 5.1.2 on 2025-02-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_transactions_transaction_receipt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_receipt_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
