# Generated by Django 5.1.2 on 2025-02-28 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_transactions_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.orderitem'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.TextField(choices=[('SALE', 'Sale'), ('ORDER_RECEIVED', 'Order Received'), ('ADJUSTMENT', 'Inventory Adjustment'), ('RETURN', 'Customer Return'), ('ORDER', 'Order')]),
        ),
    ]
