# Generated by Django 5.1.2 on 2025-02-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_transactions_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expense_date', models.DateTimeField(auto_created=True)),
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_detail', models.CharField(max_length=20)),
                ('expense_amount', models.IntegerField()),
            ],
        ),
    ]
