# Generated by Django 5.1.2 on 2025-02-28 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_changed_date', models.DateTimeField(auto_created=True)),
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_amount', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
            ],
        ),
    ]
