# Generated by Django 5.1.2 on 2025-02-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_changed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
