# Generated by Django 5.1.2 on 2025-02-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_product_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_changed_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
