# Generated by Django 5.1.6 on 2025-03-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_stock_stock_changed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='saleTime',
            field=models.DateField(auto_created=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_changed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
