# Generated by Django 5.1.6 on 2025-03-12 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_salesitem_saletime_alter_stock_stock_changed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='saleTime',
        ),
    ]
