# Generated by Django 5.1.6 on 2025-03-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_remove_salesitem_saletime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_changed_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
