# Generated by Django 5.1.6 on 2025-03-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_stock_stock_changed_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
