# Generated by Django 5.1.6 on 2025-03-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='sale_date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
