# Generated by Django 5.1.6 on 2025-03-12 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_salesitem_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='sale_date',
            field=models.DateField(verbose_name=datetime.date.today, null=True),
        ),
    ]
