# Generated by Django 5.1.6 on 2025-03-12 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_salesitem_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='sale_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
