# Generated by Django 5.1.6 on 2025-03-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_salesitem_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='sale_date',
        ),
    ]
