# Generated by Django 5.1.6 on 2025-03-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_remove_salesitem_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
