# Generated by Django 5.1.6 on 2025-03-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_transactions_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
