# Generated by Django 5.1.6 on 2025-03-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_orderitem_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
