# Generated by Django 5.1.7 on 2025-03-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0034_alter_orderitem_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="stock_changed_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
