# Generated by Django 5.1.6 on 2025-03-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_stock_stock_changed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_manufacturer',
            field=models.TextField(default=None),
        ),
    ]
