# Generated by Django 5.1.6 on 2025-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_manufacturer_alter_product_product_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='media/productPhoto')),
            ],
        ),
    ]
