# Generated by Django 5.1.6 on 2025-03-14 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_fakedatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_manufacturer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.manufacturer'),
        ),
    ]
