# Generated by Django 5.1.6 on 2025-03-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_alter_product_product_manufacturer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FakeDatabase',
        ),
    ]
