# Generated by Django 5.1.6 on 2025-03-22 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_remove_product_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_manufacturer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.manufacturer'),
        ),
    ]
