# Generated by Django 5.1.6 on 2025-04-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_manufacturer_product_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_manufacturer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.manufacturer'),
        ),
    ]
