# Generated by Django 4.2.21 on 2025-05-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0043_alter_product_product_manufacturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_total_price",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_cost",
            field=models.DecimalField(
                decimal_places=2, default=None, editable=False, max_digits=10
            ),
        ),
    ]
