# Generated by Django 5.1.2 on 2025-02-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='total_quantity',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
