# Generated by Django 5.1.2 on 2025-02-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_total_quantity_transaction_total_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
